context:
  version: "0.0.2"
  python_min: "3.11"

package:
  name: easyimaging
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/e/easyimaging/easyimaging-${{ version }}.tar.gz
  sha256: bd083caf5f62d43bc8726e5835201c774ab5925ad3117007574717f7d739123b

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling <=1.21.0
    - setuptools-git-versioning
    - pip
  run:
    - python >=${{ python_min }},<3.14
    - easyscience >=2.2.0
    - scitiff
    - essimaging
    - plopp
    - ncrystal
    - pooch

tests:
  - python:
      imports:
        - easyimaging
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Python package for bragg-edge analysis
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/easyscience/imaging-lib/

extra:
  recipe-maintainers:
    - MridulS
